<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>EnyimMemcachedCore is a Memcached client library for .NET. Add services.AddEnyimMemcached() in Startup. Inject IMemcachedClient into constructors.</Description>
    <Authors>cnblogs.com</Authors>
    <TargetFrameworks>net48;net481;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>EnyimMemcachedCore</AssemblyName>
    <PackageId>EnyimMemcachedCore</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>memcached;cache</PackageTags>
    <PackageProjectUrl>https://github.com/cnblogs/EnyimMemcachedCore</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/cnblogs/EnyimMemcachedCore</RepositoryUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);SYSLIB0011</NoWarn>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>../../key.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)'!='net48' And '$(TargetFramework)'!='net481'">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net48' Or '$(TargetFramework)'=='net481'">
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.3" />
    <PackageReference Include="System.Net.Security" Version="4.3.2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MemcachedTest, PublicKey=00240000048000009400000006020000002400005253413100040000010001007D5EB13E724D19517C303449F021E3F6041CB83D7AB85F7AFE9ACB6B521B2A7E39E4BF375900E3F0A119AE3DB493AF547A59E66EDC9C0EE5BB4602AB857DDA45F64C23A92D728D8271EEE0570205880D3F15BC7F127F007D95A8D6653FA8C80F72E0CD7DB35986BEC1834D5983BCB1AAC802118D681E34DD935AA2F07697E6B7" />
  </ItemGroup>
</Project>